INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('john', 'doe', 'john@gmail.com', 'Calle Leonardo da Vinci, 7, 41092', '9 5555 2222', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('jane', 'doe', 'jane@gmail.com', 'Calle de Velázquez, 80 Madrid', '9 8888 2222', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('richard', 'lee', 'rlee@gmail.com', 'Calle 12 entre 51 y 53', '9 0222 2635', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Caleb', 'Shields', 'pede.praesent@icloud.ca', 'Calle Leonardo da Vinci, 7, 41092', '9 8729 6232', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Sonya', 'Valentine', 'eget.mollis@protonmail.edu', '1843 Ac Ave', '9 7213 2805', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Kasimir', 'Donovan', 'libero.nec@hotmail.org', 'Ap #473-4963 Quis, St.', '9 2112 7371', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Hanae', 'Shepard', 'morbi.neque.tellus@aol.net', 'Calle Leonardo da Vinci, 7, 41092', '9 9815 7972', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Amal', 'Merrill', 'cursus.et@outlook.org', 'Ap #948-7662 Eu Road', '9 5494 6762', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Callum', 'Ferguson', 'nibh@google.net', '377-6338 Orci Rd.', '9 3746 6831', NOW())
INSERT INTO clients (name, lastname, email, address, phone, create_at) VALUES('Isaac', 'Leonard', 'auctor@aol.couk', '5211 Tempus, Street', '9 1180 8266', NOW())